"""
Genius profile seed data — mirrors the frontend geniusData.ts seed list.
All profiles are seeded with publication_status='published'.
"""

from typing import Any, Dict, List

_PROFILE_TYPES: Dict[str, str] = {
    'steve-jobs':       'public_intellectual',
    'elon-musk':        'public_intellectual',
    'bill-gates':       'public_intellectual',
    'mark-zuckerberg':  'public_intellectual',
    'noam-chomsky':     'public_intellectual',
    'jane-goodall':     'public_intellectual',
    'yuval-noah-harari':'public_intellectual',
    'daniel-kahneman':  'public_intellectual',
    'sherlock-holmes':  'fictional',
    'hermione-granger': 'fictional',
    'mr-spock':         'fictional',
    'tony-stark':       'fictional',
}

_SOURCE_NAMES: Dict[str, str] = {
    'sherlock-holmes':  'Arthur Conan Doyle stories',
    'hermione-granger': 'Harry Potter series',
    'mr-spock':         'Star Trek',
    'tony-stark':       'Marvel fiction',
}

_IMAGE_URLS: Dict[str, str] = {
    'albert-einstein':   'https://commons.wikimedia.org/wiki/Special:FilePath/Einstein_1921_by_F_Schmutzer_-_restoration.jpg',
    'isaac-newton':      'https://commons.wikimedia.org/wiki/Special:FilePath/GodfreyKneller-IsaacNewton-1689.jpg',
    'stephen-hawking':   'https://commons.wikimedia.org/wiki/Special:FilePath/Stephen_Hawking.StarChild.jpg',
    'marie-curie':       'https://commons.wikimedia.org/wiki/Special:FilePath/Marie_Curie_c1920.jpg',
    'nikola-tesla':      'https://commons.wikimedia.org/wiki/Special:FilePath/N.Tesla.JPG',
    'galileo-galilei':   'https://commons.wikimedia.org/wiki/Special:FilePath/Galileo.arp.300pix.jpg',
    'alan-turing':       'https://commons.wikimedia.org/wiki/Special:FilePath/Alan_Turing_Aged_16.jpg',
    'ada-lovelace':      'https://commons.wikimedia.org/wiki/Special:FilePath/Ada_Lovelace_portrait.jpg',
    'john-von-neumann':  'https://commons.wikimedia.org/wiki/Special:FilePath/JohnvonNeumann-LosAlamos.gif',
    'aristotle':         'https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg',
    'plato':             'https://commons.wikimedia.org/wiki/Special:FilePath/Plato_Silanion_Musei_Capitolini_MC1377.jpg',
    'socrates':          'https://commons.wikimedia.org/wiki/Special:FilePath/Socrates_Louvre.jpg',
    'immanuel-kant':     'https://commons.wikimedia.org/wiki/Special:FilePath/Immanuel_Kant_%28painted_portrait%29.jpg',
    'rene-descartes':    'https://commons.wikimedia.org/wiki/Special:FilePath/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg',
    'friedrich-nietzsche':'https://commons.wikimedia.org/wiki/Special:FilePath/Nietzsche187a.jpg',
    'leonardo-da-vinci': 'https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_self.jpg',
    'michelangelo':      'https://commons.wikimedia.org/wiki/Special:FilePath/Michelangelo_Daniele_da_Volterra_%28dettaglio%29.jpg',
    'pablo-picasso':     'https://commons.wikimedia.org/wiki/Special:FilePath/Pablo_picasso_1.jpg',
    'wolfgang-mozart':   'https://commons.wikimedia.org/wiki/Special:FilePath/Wolfgang-amadeus-mozart_1.jpg',
    'ludwig-beethoven':  'https://commons.wikimedia.org/wiki/Special:FilePath/Beethoven.jpg',
    'johann-bach':       'https://commons.wikimedia.org/wiki/Special:FilePath/Johann_Sebastian_Bach.jpg',
    'william-shakespeare':'https://commons.wikimedia.org/wiki/Special:FilePath/Chandos_portrait_of_William_Shakespeare.jpg',
    'johann-goethe':     'https://commons.wikimedia.org/wiki/Special:FilePath/Goethe_%28Stieler_1828%29.jpg',
    'leo-tolstoy':       'https://commons.wikimedia.org/wiki/Special:FilePath/L.N.Tolstoy_Prokudin-Gorsky.jpg',
    'charles-darwin':    'https://commons.wikimedia.org/wiki/Special:FilePath/Charles_Darwin_01.jpg',
    'steve-jobs':        'https://commons.wikimedia.org/wiki/Special:FilePath/Steve_Jobs_Headshot_2010-CROP.jpg',
    'elon-musk':         'https://commons.wikimedia.org/wiki/Special:FilePath/Elon_Musk_Royal_Society_%28crop2%29.jpg',
    'bill-gates':        'https://commons.wikimedia.org/wiki/Special:FilePath/Bill_Gates_2018.jpg',
    'mark-zuckerberg':   'https://commons.wikimedia.org/wiki/Special:FilePath/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg',
    'noam-chomsky':      'https://commons.wikimedia.org/wiki/Special:FilePath/Noam_Chomsky_portrait_2017_retouched.png',
    'jane-goodall':      'https://commons.wikimedia.org/wiki/Special:FilePath/Jane_Goodall_2015.jpg',
    'yuval-noah-harari': 'https://commons.wikimedia.org/wiki/Special:FilePath/Yuval_Noah_Harari_cropped.jpg',
    'daniel-kahneman':   'https://commons.wikimedia.org/wiki/Special:FilePath/Daniel_Kahneman_%283282213567%29_%28cropped%29.jpg',
}

_RAW_SEEDS: List[Dict[str, Any]] = [
    # ── Physics & Mathematics ──────────────────────────────────────────────────
    dict(id='albert-einstein', full_name='Albert Einstein', iq_score=160,
         birth_date='1879-03-14', death_date='1955-04-18',
         birth_place='Ulm, Kingdom of Württemberg, German Empire', zodiac_sign='Pisces',
         biography="Albert Einstein was a German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics. His work is also known for its influence on the philosophy of science. He is best known to the general public for his mass–energy equivalence formula E = mc², which has been dubbed \"the world's most famous equation\".",
         short_description='Theoretical physicist who developed the theory of relativity and mass-energy equivalence formula E=mc²',
         era='Modern', is_historical=True),
    dict(id='isaac-newton', full_name='Sir Isaac Newton', iq_score=190,
         birth_date='1643-01-04', death_date='1727-03-31',
         birth_place='Woolsthorpe-by-Colsterworth, Lincolnshire, England', zodiac_sign='Capricorn',
         biography='Sir Isaac Newton was an English mathematician, physicist, astronomer, theologian, and author who is widely recognised as one of the most influential scientists of all time. His book Philosophiæ Naturalis Principia Mathematica established classical mechanics and laid the foundations for modern physics.',
         short_description='Mathematician and physicist who formulated the laws of motion and universal gravitation',
         era='Enlightenment', is_historical=True),
    dict(id='stephen-hawking', full_name='Stephen Hawking', iq_score=160,
         birth_date='1942-01-08', death_date='2018-03-14',
         birth_place='Oxford, England', zodiac_sign='Capricorn',
         biography='Stephen William Hawking was an English theoretical physicist, cosmologist, and author. He was director of research at the Centre for Theoretical Cosmology at the University of Cambridge and made groundbreaking contributions to the fields of cosmology, general relativity and quantum gravity.',
         short_description='Theoretical physicist known for his work on black holes and cosmology',
         era='Contemporary', is_historical=True),
    dict(id='marie-curie', full_name='Marie Curie', iq_score=185,
         birth_date='1867-11-07', death_date='1934-07-04',
         birth_place='Warsaw, Poland', zodiac_sign='Scorpio',
         biography='Marie Skłodowska Curie was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize, the first person and the only woman to win the Nobel Prize twice, and the only person to win the Nobel Prize in two different scientific fields.',
         short_description='Pioneering physicist and chemist who discovered radium and polonium, first woman to win Nobel Prize',
         era='Modern', is_historical=True),
    dict(id='nikola-tesla', full_name='Nikola Tesla', iq_score=195,
         birth_date='1856-07-10', death_date='1943-01-07',
         birth_place='Smiljan, Austrian Empire', zodiac_sign='Cancer',
         biography='Nikola Tesla was a Serbian-American inventor, electrical engineer, mechanical engineer, and futurist best known for his contributions to the design of the modern alternating current electricity supply system. His patents and theoretical work formed the basis of modern AC electricity.',
         short_description='Inventor and electrical engineer who pioneered alternating current (AC) electrical systems',
         era='Modern', is_historical=True),
    dict(id='galileo-galilei', full_name='Galileo Galilei', iq_score=185,
         birth_date='1564-02-15', death_date='1642-01-08',
         birth_place='Pisa, Duchy of Florence, Italy', zodiac_sign='Aquarius',
         biography="Galileo di Vincenzo Bonaiuti de' Galilei was an Italian astronomer, physicist and engineer. He has been called the 'father of observational astronomy', the 'father of modern physics', and the 'father of the scientific method'. His contributions to observational astronomy include telescopic confirmation of the phases of Venus.",
         short_description='Astronomer and physicist called the father of modern science and scientific method',
         era='Renaissance', is_historical=True),

    # ── Computer Science & Technology ─────────────────────────────────────────
    dict(id='alan-turing', full_name='Alan Turing', iq_score=185,
         birth_date='1912-06-23', death_date='1954-06-07',
         birth_place='Maida Vale, London, England', zodiac_sign='Cancer',
         biography='Alan Mathison Turing was an English mathematician, computer scientist, logician, cryptanalyst, philosopher, and theoretical biologist. Turing was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine.',
         short_description='Father of computer science and artificial intelligence, broke the Enigma code in WWII',
         era='Modern', is_historical=True),
    dict(id='ada-lovelace', full_name='Ada Lovelace', iq_score=170,
         birth_date='1815-12-10', death_date='1852-11-27',
         birth_place='London, England', zodiac_sign='Sagittarius',
         biography="Augusta Ada King, Countess of Lovelace was an English mathematician and writer, chiefly known for her work on Charles Babbage's proposed mechanical general-purpose computer, the Analytical Engine. She is often regarded as the first computer programmer.",
         short_description='First computer programmer who wrote the first algorithm for a computing machine',
         era='Industrial', is_historical=True),
    dict(id='john-von-neumann', full_name='John von Neumann', iq_score=190,
         birth_date='1903-12-28', death_date='1957-02-08',
         birth_place='Budapest, Austria-Hungary', zodiac_sign='Capricorn',
         biography='John von Neumann was a Hungarian-American mathematician, physicist, computer scientist, engineer and polymath. Von Neumann made major contributions to many fields, including mathematics, physics, economics, computing, and statistics. He was a pioneer of the application of operator theory to quantum mechanics.',
         short_description='Polymath who pioneered computer architecture, game theory, and quantum mechanics',
         era='Modern', is_historical=True),

    # ── Philosophy ────────────────────────────────────────────────────────────
    dict(id='aristotle', full_name='Aristotle', iq_score=180,
         birth_date='-0384-01-01', death_date='-0322-01-01',
         birth_place='Stagira, Chalcidice, Greece', zodiac_sign=None,
         biography='Aristotle was a Greek philosopher and polymath during the Classical period in Ancient Greece. Taught by Plato, he was the founder of the Lyceum and the Peripatetic school of philosophy. His writings cover many subjects including physics, biology, zoology, metaphysics, logic, ethics, aesthetics, poetry, theatre, music, rhetoric, psychology, linguistics, economics, politics, and government.',
         short_description='Ancient Greek philosopher who studied under Plato and tutored Alexander the Great',
         era='Ancient', is_historical=True),
    dict(id='plato', full_name='Plato', iq_score=175,
         birth_date='-0428-01-01', death_date='-0348-01-01',
         birth_place='Athens, Greece', zodiac_sign=None,
         biography='Plato was an Athenian philosopher during the Classical period in Ancient Greece, founder of the Platonist school of thought and the Academy, the first institution of higher learning in the Western world. He is widely considered a pivotal figure in the history of Ancient Greek and Western philosophy.',
         short_description='Founder of the Academy and student of Socrates, developed theory of Forms',
         era='Ancient', is_historical=True),
    dict(id='socrates', full_name='Socrates', iq_score=180,
         birth_date='-0470-01-01', death_date='-0399-01-01',
         birth_place='Athens, Greece', zodiac_sign=None,
         biography='Socrates was a Greek philosopher from Athens who is credited as one of the founders of Western philosophy, and as being the first moral philosopher of the Western ethical tradition of thought. An enigmatic figure, he made no writings, and is known chiefly through the accounts of classical writers composing after his lifetime.',
         short_description='Father of Western philosophy known for Socratic method of inquiry',
         era='Ancient', is_historical=True),
    dict(id='immanuel-kant', full_name='Immanuel Kant', iq_score=175,
         birth_date='1724-04-22', death_date='1804-02-12',
         birth_place='Königsberg, Prussia', zodiac_sign='Taurus',
         biography='Immanuel Kant was a German philosopher and one of the central Enlightenment thinkers. His comprehensive and systematic works in epistemology, metaphysics, ethics, and aesthetics have made him one of the most influential figures in modern Western philosophy.',
         short_description='Enlightenment philosopher who developed categorical imperative and transcendental idealism',
         era='Enlightenment', is_historical=True),
    dict(id='rene-descartes', full_name='René Descartes', iq_score=180,
         birth_date='1596-03-31', death_date='1650-02-11',
         birth_place='La Haye en Touraine, France', zodiac_sign='Aries',
         biography='René Descartes was a French philosopher, mathematician, and scientist. Dubbed the father of modern philosophy, much of subsequent Western philosophy is a response to his writings. He is famous for having made an important connection between geometry and algebra, which allowed for the solving of geometrical problems by way of algebraic equations.',
         short_description='Father of modern philosophy, known for "I think, therefore I am" and analytical geometry',
         era='Enlightenment', is_historical=True),
    dict(id='friedrich-nietzsche', full_name='Friedrich Nietzsche', iq_score=170,
         birth_date='1844-10-15', death_date='1900-08-25',
         birth_place='Röcken, Prussia', zodiac_sign='Libra',
         biography='Friedrich Wilhelm Nietzsche was a German philosopher, cultural critic, composer, poet, and philologist whose work has exerted a profound influence on modern intellectual history. His critiques of contemporary culture, religion, and philosophy centered on a basic question regarding the foundation of values and morality.',
         short_description='Philosopher who developed concepts of Übermensch and eternal recurrence',
         era='Modern', is_historical=True),

    # ── Arts & Renaissance ────────────────────────────────────────────────────
    dict(id='leonardo-da-vinci', full_name='Leonardo da Vinci', iq_score=200,
         birth_date='1452-04-15', death_date='1519-05-02',
         birth_place='Vinci, Republic of Florence', zodiac_sign='Aries',
         biography='Leonardo di ser Piero da Vinci was an Italian polymath of the High Renaissance who was active as a painter, draughtsman, engineer, scientist, theorist, sculptor and architect. His areas of interest included invention, drawing, painting, sculpting, architecture, science, music, mathematics, engineering, literature, anatomy, geology, astronomy, botany, writing, history, and cartography.',
         short_description='Ultimate Renaissance polymath: artist, inventor, scientist, and visionary genius',
         era='Renaissance', is_historical=True),
    dict(id='michelangelo', full_name='Michelangelo Buonarroti', iq_score=180,
         birth_date='1475-03-06', death_date='1564-02-18',
         birth_place='Caprese, Republic of Florence', zodiac_sign='Pisces',
         biography='Michelangelo di Lodovico Buonarroti Simoni, known best as simply Michelangelo, was an Italian sculptor, painter, architect and poet of the High Renaissance born in the Republic of Florence. His work demonstrated a blend of psychological insight, physical realism and intensity never before seen.',
         short_description='Renaissance sculptor, painter, and architect who created David and the Sistine Chapel ceiling',
         era='Renaissance', is_historical=True),
    dict(id='pablo-picasso', full_name='Pablo Picasso', iq_score=175,
         birth_date='1881-10-25', death_date='1973-04-08',
         birth_place='Málaga, Spain', zodiac_sign='Scorpio',
         biography='Pablo Ruiz Picasso was a Spanish painter, sculptor, printmaker, ceramicist and theatre designer who spent most of his adult life in France. Regarded as one of the most influential artists of the 20th century, he is known for co-founding the Cubist movement and for the wide variety of styles that he helped develop and explore.',
         short_description='Co-founder of Cubism and one of the most influential artists of the 20th century',
         era='Modern', is_historical=True),

    # ── Music ─────────────────────────────────────────────────────────────────
    dict(id='wolfgang-mozart', full_name='Wolfgang Amadeus Mozart', iq_score=165,
         birth_date='1756-01-27', death_date='1791-12-05',
         birth_place='Salzburg, Austria', zodiac_sign='Aquarius',
         biography='Wolfgang Amadeus Mozart was a prolific and influential composer of the Classical period. Born in Salzburg, Mozart showed prodigious ability from his earliest childhood. Already competent on keyboard and violin, he composed from the age of five and performed before European royalty.',
         short_description='Prolific Classical composer who created over 600 works including operas, symphonies, and concertos',
         era='Enlightenment', is_historical=True),
    dict(id='ludwig-beethoven', full_name='Ludwig van Beethoven', iq_score=165,
         birth_date='1770-12-17', death_date='1827-03-26',
         birth_place='Bonn, Germany', zodiac_sign='Sagittarius',
         biography='Ludwig van Beethoven was a German composer and pianist. Beethoven remains one of the most admired composers in the history of Western music; his works rank amongst the most performed of the classical music repertoire. He continued to compose even after losing his hearing.',
         short_description='Revolutionary composer who bridged Classical and Romantic eras, composed while deaf',
         era='Enlightenment', is_historical=True),
    dict(id='johann-bach', full_name='Johann Sebastian Bach', iq_score=165,
         birth_date='1685-03-31', death_date='1750-07-28',
         birth_place='Eisenach, Germany', zodiac_sign='Aries',
         biography='Johann Sebastian Bach was a German composer and musician of the Baroque period. He is known for instrumental compositions such as the Brandenburg Concertos and the Goldberg Variations, and for vocal music such as the St Matthew Passion and the Mass in B minor.',
         short_description='Baroque composer whose works are fundamental to Western classical music',
         era='Enlightenment', is_historical=True),

    # ── Literature ────────────────────────────────────────────────────────────
    dict(id='william-shakespeare', full_name='William Shakespeare', iq_score=210,
         birth_date='1564-04-26', death_date='1616-04-23',
         birth_place='Stratford-upon-Avon, England', zodiac_sign='Taurus',
         biography="William Shakespeare was an English playwright, poet, and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist. He is often called England's national poet and the \"Bard of Avon\". His plays have been translated into every major living language and are performed more often than those of any other playwright.",
         short_description='Greatest English playwright and poet, wrote 37 plays and 154 sonnets',
         era='Renaissance', is_historical=True),
    dict(id='johann-goethe', full_name='Johann Wolfgang von Goethe', iq_score=210,
         birth_date='1749-08-28', death_date='1832-03-22',
         birth_place='Frankfurt, Germany', zodiac_sign='Virgo',
         biography='Johann Wolfgang von Goethe was a German writer and statesman. His works include: four novels; epic and lyric poetry; prose and verse dramas; memoirs; an autobiography; literary and aesthetic criticism; and treatises on botany, anatomy, and colour. In addition, numerous literary and scientific fragments, more than 10,000 letters, and nearly 3,000 drawings by him have survived.',
         short_description='German polymath and author of Faust, considered the greatest German literary figure',
         era='Enlightenment', is_historical=True),
    dict(id='leo-tolstoy', full_name='Leo Tolstoy', iq_score=170,
         birth_date='1828-09-09', death_date='1910-11-20',
         birth_place='Yasnaya Polyana, Russia', zodiac_sign='Virgo',
         biography='Count Lev Nikolayevich Tolstoy, usually referred to in English as Leo Tolstoy, was a Russian writer who is regarded as one of the greatest authors of all time. He received nominations for the Nobel Prize in Literature every year from 1902 to 1906 and for the Nobel Peace Prize in 1901, 1902, and 1909.',
         short_description='Russian author of War and Peace and Anna Karenina, master of realistic fiction',
         era='Modern', is_historical=True),

    # ── Biology & Natural Sciences ────────────────────────────────────────────
    dict(id='charles-darwin', full_name='Charles Darwin', iq_score=165,
         birth_date='1809-02-12', death_date='1882-04-19',
         birth_place='Shrewsbury, England', zodiac_sign='Aquarius',
         biography='Charles Robert Darwin was an English naturalist, geologist and biologist, best known for his contributions to the science of evolution. His proposition that all species of life have descended over time from common ancestors is now widely accepted and considered a foundational concept in science.',
         short_description='Naturalist who developed theory of evolution by natural selection',
         era='Industrial', is_historical=True),

    # ── Modern Innovators ─────────────────────────────────────────────────────
    dict(id='steve-jobs', full_name='Steve Jobs', iq_score=160,
         birth_date='1955-02-24', death_date='2011-10-05',
         birth_place='San Francisco, California, USA', zodiac_sign='Pisces',
         biography='Steven Paul Jobs was an American entrepreneur, industrial designer, business magnate, media proprietor, and investor. He was the co-founder, chairman, and CEO of Apple Inc. Jobs is widely recognized as a pioneer of the personal computer revolution and for his influential career in the computer and consumer electronics fields.',
         short_description='Co-founder of Apple Inc., revolutionized personal computing, smartphones, and digital music',
         era='Contemporary', is_historical=False),
    dict(id='elon-musk', full_name='Elon Musk', iq_score=160,
         birth_date='1971-06-28', death_date=None,
         birth_place='Pretoria, South Africa', zodiac_sign='Cancer',
         biography='Elon Reeve Musk is a business magnate and investor. He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter; founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation.',
         short_description='Entrepreneur leading SpaceX, Tesla, and advancing sustainable energy and space exploration',
         era='Contemporary', is_historical=False),
    dict(id='bill-gates', full_name='Bill Gates', iq_score=160,
         birth_date='1955-10-28', death_date=None,
         birth_place='Seattle, Washington, USA', zodiac_sign='Scorpio',
         biography='William Henry Gates III is an American business magnate, software developer, investor, author, and philanthropist. He is best known as the co-founder of Microsoft Corporation. During his career at Microsoft, Gates held the positions of chairman, chief executive officer, president and chief software architect.',
         short_description='Co-founder of Microsoft, pioneered personal computing revolution and global philanthropy',
         era='Contemporary', is_historical=False),
    dict(id='mark-zuckerberg', full_name='Mark Zuckerberg', iq_score=152,
         birth_date='1984-05-14', death_date=None,
         birth_place='White Plains, New York, USA', zodiac_sign='Taurus',
         biography='Mark Elliot Zuckerberg is an American media magnate, internet entrepreneur, and philanthropist. He is known for co-founding the social media website Facebook and its parent company Meta Platforms (formerly Facebook, Inc.), of which he is the chairman, chief executive officer, and controlling shareholder.',
         short_description='Co-founder and CEO of Meta (Facebook), transformed global social connectivity',
         era='Contemporary', is_historical=False),

    # ── Public Intellectuals ──────────────────────────────────────────────────
    dict(id='noam-chomsky', full_name='Noam Chomsky', iq_score=None,
         birth_date='1928-12-07', death_date=None,
         birth_place='Philadelphia, Pennsylvania, USA', zodiac_sign='Sagittarius',
         biography='Noam Chomsky is a linguist, philosopher, cognitive scientist, historian, and public intellectual. This profile highlights publicly documented influence in linguistics and political analysis without making a verified IQ claim.',
         short_description='Public intellectual known for linguistics, cognitive science, and political analysis',
         era='Contemporary', is_historical=False),
    dict(id='jane-goodall', full_name='Jane Goodall', iq_score=None,
         birth_date='1934-04-03', death_date=None,
         birth_place='London, England', zodiac_sign='Aries',
         biography='Jane Goodall is a primatologist, ethologist, and conservationist known for decades of chimpanzee research. This profile emphasizes expertise, research impact, and public education rather than IQ.',
         short_description='Primatologist and conservationist known for field research and public science education',
         era='Contemporary', is_historical=False),
    dict(id='yuval-noah-harari', full_name='Yuval Noah Harari', iq_score=None,
         birth_date='1976-02-24', death_date=None,
         birth_place='Kiryat Ata, Israel', zodiac_sign='Pisces',
         biography='Yuval Noah Harari is a historian and author known for public writing on human history, technology, and society. This profile treats his ranking as an expertise and influence signal, not as a verified IQ score.',
         short_description='Historian and public author known for broad work on history, technology, and society',
         era='Contemporary', is_historical=False),
    dict(id='daniel-kahneman', full_name='Daniel Kahneman', iq_score=None,
         birth_date='1934-03-05', death_date='2024-03-27',
         birth_place='Tel Aviv, Mandatory Palestine', zodiac_sign='Pisces',
         biography='Daniel Kahneman was a psychologist and Nobel laureate whose work on judgment, decision-making, and behavioral economics shaped modern understanding of human cognition. This profile uses awards and research influence rather than IQ.',
         short_description='Psychologist and Nobel laureate known for judgment, decision-making, and behavioral economics',
         era='Contemporary', is_historical=False),

    # ── Fictional Archetypes ──────────────────────────────────────────────────
    dict(id='sherlock-holmes', full_name='Sherlock Holmes', iq_score=None,
         birth_date=None, death_date=None,
         birth_place='London, England', zodiac_sign=None,
         biography='Sherlock Holmes is a fictional consulting detective created by Arthur Conan Doyle. This profile is included as a literary benchmark for observation, deductive reasoning, pattern recognition, and analytical discipline rather than as a real-world IQ claim.',
         short_description='Fictional detective used as a benchmark for observation, deduction, and analytical reasoning',
         era='Modern', is_historical=False),
    dict(id='hermione-granger', full_name='Hermione Granger', iq_score=None,
         birth_date=None, death_date=None,
         birth_place='Fictional United Kingdom', zodiac_sign=None,
         biography='Hermione Granger is a fictional character from the Harry Potter series. This profile frames her as a study-skills and applied-knowledge archetype, not as a real person or verified psychological profile.',
         short_description='Fictional learner archetype for disciplined study, memory, and applied problem solving',
         era='Contemporary', is_historical=False),
    dict(id='mr-spock', full_name='Spock', iq_score=None,
         birth_date=None, death_date=None,
         birth_place='Vulcan', zodiac_sign=None,
         biography='Spock is a fictional Star Trek character. This profile is used as a logic, composure, and systems-thinking archetype rather than a literal intelligence comparison.',
         short_description='Fictional logic archetype for systems thinking, composure, and analytical judgment',
         era='Contemporary', is_historical=False),
    dict(id='tony-stark', full_name='Tony Stark', iq_score=None,
         birth_date=None, death_date=None,
         birth_place='Fictional United States', zodiac_sign=None,
         biography='Tony Stark is a fictional Marvel character. This profile represents a fictional engineering and invention archetype and should not be read as a real psychological assessment.',
         short_description='Fictional engineering archetype for invention, rapid prototyping, and technical creativity',
         era='Contemporary', is_historical=False),
]


def _build_profile(raw: Dict[str, Any]) -> Dict[str, Any]:
    genius_id = raw['id']
    is_historical = raw.get('is_historical', True)

    profile_type = _PROFILE_TYPES.get(genius_id)
    if not profile_type:
        profile_type = 'historical' if is_historical else 'public_intellectual'

    is_fictional = profile_type == 'fictional'

    source_name = _SOURCE_NAMES.get(genius_id)
    if source_name:
        editorial_note = f'Fictional profile from {source_name}. Use as an archetype, not a real person comparison.'
        source_url = None
    else:
        editorial_note = 'Editorial profile for learning inspiration. Intelligence labels are contextual and should be read as estimates where shown.'
        name_slug = raw['full_name'].replace(' ', '_')
        source_url = f'https://en.wikipedia.org/wiki/{name_slug}'

    return {
        **raw,
        'profile_type':       profile_type,
        'is_fictional':       is_fictional,
        'is_historical':      is_historical,
        'editorial_note':     editorial_note,
        'source_url':         source_url,
        'publication_status': 'published',
        'profile_image_url':  _IMAGE_URLS.get(genius_id),
    }


GENIUS_SEEDS: List[Dict[str, Any]] = [_build_profile(r) for r in _RAW_SEEDS]
