"""add parent replis to comments

Revision ID: 0210338ec96c
Revises: e88f31882e31
Create Date: 2026-04-29 02:18:04.807191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0210338ec96c'
down_revision: Union[str, Sequence[str], None] = 'e88f31882e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_comments', 'course_comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_comments', type_='foreignkey')
    op.drop_column('course_comments', 'parent_id')
    # ### end Alembic commands ###
