"""add resolved to comments

Revision ID: 1c68b51cbfb4
Revises: 0210338ec96c
Create Date: 2026-04-29 20:08:59.151853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c68b51cbfb4'
down_revision: Union[str, Sequence[str], None] = '0210338ec96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_comments', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_comments', 'resolved')
    # ### end Alembic commands ###
