"""add status to psycology register remove psychologist_status

Revision ID: 1f6b479704f4
Revises: 7669c05b1afc
Create Date: 2026-05-06 11:08:23.613501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6b479704f4'
down_revision: Union[str, Sequence[str], None] = '7669c05b1afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychologist_profiles', 'psychologist_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologist_profiles', sa.Column('psychologist_status', postgresql.ENUM('pending', 'approved', 'rejected', name='psychologist_profile_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
