"""add_attachments update

Revision ID: 25d5c9baf501
Revises: 5bda1c35b498
Create Date: 2026-04-07 16:00:24.477168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d5c9baf501'
down_revision: Union[str, Sequence[str], None] = '5bda1c35b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'thubnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thubnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
