"""make_psychologist_hourly_rate_nullable

Revision ID: 3689245ec16c
Revises: 4515fc169ddf
Create Date: 2026-05-15 21:43:57.119555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3689245ec16c'
down_revision: Union[str, Sequence[str], None] = '4515fc169ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologist_profiles', 'hourly_rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologist_profiles', 'hourly_rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
