"""add_attachments update_2

Revision ID: 4110b871c90c
Revises: 25d5c9baf501
Create Date: 2026-04-07 16:03:49.550740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4110b871c90c'
down_revision: Union[str, Sequence[str], None] = '25d5c9baf501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thumbnail', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'attachments', ['thumbnail'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'thumbnail')
    # ### end Alembic commands ###
