"""add_attachments update

Revision ID: 5bda1c35b498
Revises: b6f677814188
Create Date: 2026-04-07 15:59:50.300876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bda1c35b498'
down_revision: Union[str, Sequence[str], None] = 'b6f677814188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thubnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'thubnail')
    # ### end Alembic commands ###
