"""make_course_activity_per_user_per_course

Revision ID: 5e88becdc097
Revises: 85c4e9f2378c
Create Date: 2026-05-16 15:39:46.426612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e88becdc097'
down_revision: Union[str, Sequence[str], None] = '85c4e9f2378c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_activity_user_id_key'), 'course_activity', type_='unique')
    op.create_unique_constraint('uq_course_activity_user_course', 'course_activity', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_course_activity_user_course', 'course_activity', type_='unique')
    op.create_unique_constraint(op.f('course_activity_user_id_key'), 'course_activity', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
