"""add_attachments update_3

Revision ID: 6b5ea1120583
Revises: 4110b871c90c
Create Date: 2026-04-07 16:55:58.274291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5ea1120583'
down_revision: Union[str, Sequence[str], None] = '4110b871c90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
