"""add array fields to psychologist_profiles

Revision ID: 779cf98b83bf
Revises: 3462b16fc486
Create Date: 2026-04-13 19:22:19.572755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779cf98b83bf'
down_revision: Union[str, Sequence[str], None] = '3462b16fc486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psychologist_profiles', sa.Column('education_and_qualifications', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('psychologist_profiles', sa.Column('certification_and_additional_training', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psychologist_profiles', 'certification_and_additional_training')
    op.drop_column('psychologist_profiles', 'education_and_qualifications')
    # ### end Alembic commands ###
