"""add sections psychologist invites

Revision ID: ba0ec9754a9a
Revises: 0a70cfc4e99b
Create Date: 2026-03-26 22:41:25.560135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba0ec9754a9a'
down_revision: Union[str, Sequence[str], None] = '0a70cfc4e99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychologist_invites',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'expired', name='invite_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('course_collaborators',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('co-instructor', 'editor', 'reviewer', 'verifier', name='collaborator_role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('sub_title', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('language', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('discount', sa.Numeric(), nullable=True))
    op.add_column('courses', sa.Column('thubnail', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('course_goals', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('learning_objectives', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('prerequisites', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('courses', sa.Column('who_this_course_is_for', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('enable_discussions', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('enable_reviews', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('enable_certificates', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('maximum_students', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('section_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('lessons_course_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'sections', ['section_id'], ['id'])
    op.drop_column('lessons', 'course_id')
    op.drop_column('lessons', 'module_id')
    op.add_column('psychologist_profiles', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('psychologist_profiles', sa.Column('years_of_experience', sa.String(), nullable=True))
    op.add_column('psychologist_profiles', sa.Column('about_you', sa.Text(), nullable=True))
    op.alter_column('psychologist_profiles', 'specialization',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.alter_column('psychologist_profiles', 'specialization',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('psychologist_profiles', 'about_you')
    op.drop_column('psychologist_profiles', 'years_of_experience')
    op.drop_column('psychologist_profiles', 'license_number')
    op.add_column('lessons', sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_course_id_fkey'), 'lessons', 'courses', ['course_id'], ['id'])
    op.drop_column('lessons', 'section_id')
    op.drop_column('courses', 'maximum_students')
    op.drop_column('courses', 'enable_certificates')
    op.drop_column('courses', 'enable_reviews')
    op.drop_column('courses', 'enable_discussions')
    op.drop_column('courses', 'who_this_course_is_for')
    op.drop_column('courses', 'prerequisites')
    op.drop_column('courses', 'learning_objectives')
    op.drop_column('courses', 'course_goals')
    op.drop_column('courses', 'thubnail')
    op.drop_column('courses', 'discount')
    op.drop_column('courses', 'language')
    op.drop_column('courses', 'sub_title')
    op.drop_table('sections')
    op.drop_table('course_collaborators')
    op.drop_table('psychologist_invites')
    # ### end Alembic commands ###
