"""add_attachments update_4

Revision ID: d73d7cf4fd88
Revises: 6b5ea1120583
Create Date: 2026-04-07 16:59:43.669068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73d7cf4fd88'
down_revision: Union[str, Sequence[str], None] = '6b5ea1120583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_image', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'attachments', ['cover_image'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'cover_image')
    # ### end Alembic commands ###
