"""updated lesson to fk from 1t1

Revision ID: db198a9c37d0
Revises: c31b8a1d2f44
Create Date: 2026-04-15 13:05:57.857233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db198a9c37d0'
down_revision: Union[str, Sequence[str], None] = 'c31b8a1d2f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
