"""add genius profile

Revision ID: ed05dbe82f34
Revises: 6528306dbea1
Create Date: 2026-06-24 22:10:46.616279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed05dbe82f34'
down_revision: Union[str, Sequence[str], None] = '6528306dbea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genius_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('iq_score', sa.Integer(), nullable=True),
    sa.Column('iq_score_label', sa.String(), nullable=False),
    sa.Column('iq_score_note', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('death_date', sa.String(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=False),
    sa.Column('zodiac_sign', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('era', sa.String(), nullable=False),
    sa.Column('profile_type', sa.String(), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('editorial_note', sa.Text(), nullable=False),
    sa.Column('publication_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genius_profiles_slug'), 'genius_profiles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genius_profiles_slug'), table_name='genius_profiles')
    op.drop_table('genius_profiles')
    # ### end Alembic commands ###
